// This code was generated by a GPT-2 algorithm.

/* Code parsing function
 * FIXME: this function panics if it encounters comment delimeters in
 * string literals
 */
fn parse(code: & String, context: CodeParseContext) -> Result<Parser<String>> {

        let comment_delimeter = context.comment_delimeters;
        let comment_delimiter = comment_delimeter.into_comment_delimiter();
        do {
            // FIXME: This should return a parser to parse any other comments in string literals.
            let result = parser;

            // FIXME: This should set a breakpoint at the end of each line as well.
            for (span, line) in match context.line_starts {

                    // FIXME: This should get the current start of the comment, not the comment delimiter.
                    let start = step(line, comment_delimiter);

                    // FIXME: This should set a breakpoint at the start of the line as well.
                    let breakpoint = breakpoint(start);

                    // FIXME: This should set a breakpoint
